repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/Cretezy/flutter-format-pre-commit
    rev: "4a1df675bb74dea371c17934933e257e46f8dd98"
    hooks:
      - id: flutter-format
        exclude: lib/src/avatar.dart # Exclude the avatar widget
  - repo: https://github.com/dluksza/flutter-analyze-pre-commit
    rev: "0bfdb7415bb2d02794a884bf2b763a92772001eb"
    hooks:
      - id: flutter-analyze
