name: basic_authentication_flutter_challenge
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  awesome_snackbar_content: ^0.0.8
  circle_nav_bar: 1.0.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  flutter_svg: ^1.1.5
  http: ^0.13.5
  liquid_pull_to_refresh: ^3.0.1
  lottie: ^1.3.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
