name: flutter mobsfscan

on:
  push:
    branches: [master, main, release/**]
  pull_request:
    branches: [master, main, release/**]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Set-up Java
        uses: actions/setup-java@v1
        with:
          java-version: 12.x
      - name: Set-up Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable" # or: 'beta', 'dev' or 'master'
      - name: Flutter Install Dependencies
        run: flutter pub get
      - name: Flutter Test
        run: flutter test
      - name: Flutter Build
        run: flutter build apk
      - name: Fix Permissions for MobSF Docker
        run: |
          set -e
          sudo mkdir -p /home/runner/work/_temp/_github_home
          sudo chown -R 9901:9901 /home/runner/work/_temp/_github_home

          sudo mkdir -p /home/runner/work/$REPO_NAME/$REPO_NAME
          sudo chown -R 9901:9901 /home/runner/work/$REPO_NAME/$REPO_NAME
        env:
          REPO_NAME: "${{ github.event.repository.name }}"
      - name: Run MobSF Analysis
        uses: fundacaocerti/mobsf-action@v1.7.1
        env:
          INPUT_FILE_NAME: build/app/outputs/flutter-apk/app-release.apk
          SCAN_TYPE: apk
          OUTPUT_FILE_NAME: mobsf-report
      - name: Cleanup MobSF Permissions
        run: |
          set -e
          sudo chown -R runner:docker /home/runner/work/_temp/_github_home
          sudo chown -R runner:docker /home/runner/work/$REPO_NAME/$REPO_NAME
        env:
          REPO_NAME: "${{ github.event.repository.name }}"
      - name: Upload MobSF Analysis PDF Result
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-report.pdf
          path: mobsf-report.pdf
      - name: Upload MobSF Analysis JSON Result
        uses: actions/upload-artifact@v2
        with:
          name: mobsf-report.json
          path: mobsf-report.json
